name: Create Comment

on:
  fork:
  push:
    branches: [ master ]
  issues:
    types: [ opened ]
  issue_comment:
    types: [ created ]
  pull_request_target:
    types: [ opened ]
  pull_request_review_comment:
    types: [ created ]


jobs:
  create_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-create-comment@v1
        if: ${{ startsWith(github.event.comment.body, '/hello') }}
        with:
          github_token: ${{ secrets.github_token }}
          body: |
            Hello, @${{ github.actor }}!
