on:
  fork:
  push:
    branches: [ master ]
  issues:
    types: [ opened ]
  issue_comment:
    types: [ created ]
  pull_request_target:
    types: [ opened ]
  pull_request_review_comment:
    types: [ created ]

jobs:

  Welcome:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'It''s great having you contribute to this community/repository Thank you for raising an <strong>Issue</strong>! Welcome to our GitHub community.If you would love to involve in open-source, then you are in the right community'
        pr-message: 'It''s great having you contribute to this community. Thank you for creating a <strong>Pull Request</strong>! Welcome to our GitHub community.If you would love to involve in open-source, then you are in the right community.'
