on: pull_request

jobs:
  example_comment_pr:
    runs-on: Ubuntu-20.04
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Thanks for contributing !'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
