on:
  fork:
  push:
    branches: [ master ]
  issues:
    types: [ opened ]
  issue_comment:
    types: [ created ]
  pull_request_target:
    types: [ opened ]
  pull_request_review_comment:
    types: [ created ]

jobs:
  Welcome:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '<h2>It''s great having you contribute to this community/repository</h2> <P>Thank you for raising an <strong>Issue</strong>! Welcome to our GitHub community</p> <p>If you would love to involve in open-source, then you are in the right community. To be a part of us, kindly join us via our <a href = "https://discord.gg/c6RhGwcP5b">discord channel</a> and our <a href = "https://github.com/chryz-hub">GitHub organization</a>. We help to build open source giants/ great contributors relevant to the society and themselves personally.</p> Are you yet to understand something, feel free to ask us!'
        pr-message: '<h2>It''s great having you contribute to this community and project(repo)</h2> <P>Thank you for creating a <strong>Pull Request</strong>! Welcome to our GitHub community</p> <p>If you would love to involve in open-source, then you are in the right community. To be a part of us, kindly join us via our <a href = "https://discord.gg/c6RhGwcP5b">discord channel</a> and our <a href = "https://github.com/chryz-hub">GitHub organization</a>. We help to build open source giants/ great contributors relevant to the society and themselves personally.</p> Are you yet to understand something, feel free to ask us!'
